# Pandas

In [2]:
import pandas as pd
import numpy as np

In [3]:
data = [
    ["John", 98556556846],
    ["Harsh", 64524248226],
    ["Heet", 89824565135],
    ["Dhruvi", 48486318987]
]

In [4]:
df = pd.DataFrame(data, columns=["Name", "Phone"])

In [5]:
df

Name        Phone
0    John  98556556846
1   Harsh  64524248226
2    Heet  89824565135
3  Dhruvi  48486318987

In [6]:
df['Age'] = [34, 20, 45, 22]

In [7]:
df

Name        Phone  Age
0    John  98556556846   34
1   Harsh  64524248226   20
2    Heet  89824565135   45
3  Dhruvi  48486318987   22

In [8]:
df.insert(2, "Marks", [78, 99, 84, 90])

In [9]:
df

Name        Phone  Marks  Age
0    John  98556556846     78   34
1   Harsh  64524248226     99   20
2    Heet  89824565135     84   45
3  Dhruvi  48486318987     90   22

In [10]:
# df.drop("Marks", axis=1) --> Gives deleted df, original doesn't change
# df.drop("Marks", axis=1, inplace=True) --> Deleted from original df

In [11]:
df

Name        Phone  Marks  Age
0    John  98556556846     78   34
1   Harsh  64524248226     99   20
2    Heet  89824565135     84   45
3  Dhruvi  48486318987     90   22

In [12]:
data = {
    'a' : [7, 3, np.NaN],
    'b' : [3, np.NaN, np.NaN],
    'c' : [9, 3, 1],    
}

In [13]:
df = pd.DataFrame(data)

In [14]:
df

a    b  c
0  7.0  3.0  9
1  3.0  NaN  3
2  NaN  NaN  1

In [15]:
# Does not change original df
df.dropna()
df.fillna(9999)

a       b  c
0     7.0     3.0  9
1     3.0  9999.0  3
2  9999.0  9999.0  1

In [16]:
df

a    b  c
0  7.0  3.0  9
1  3.0  NaN  3
2  NaN  NaN  1

In [17]:
df['c'].mean()

4.333333333333333

In [18]:
np.mean(df['c'])

4.333333333333333

In [19]:
df['a'] = df['a'].fillna(df['a'].mean())
df['b'] = df['b'].fillna(df['b'].mean())
df['c'] = df['c'].fillna(df['c'].mean())

In [20]:
df

a    b  c
0  7.0  3.0  9
1  3.0  3.0  3
2  5.0  3.0  1

In [21]:
df = pd.read_csv('mydataset.csv')

In [22]:
df

Name   Age Gender  Height  Weight
0    Alice  25.0      F     5.5    65.0
1      Bob   NaN      M     6.0    80.0
2  Charlie  35.0    NaN     NaN    77.0
3    David  45.0      M     5.8     NaN
4   Edward  55.0      M     5.9    88.0
5    Frank  40.0      M     6.1    90.0
6   George  65.0      M     6.2    75.0
7     Hank  35.0      M     5.9    77.0
8    Alice  25.0      F     5.5    65.0

In [23]:
# df['Age'] = df['Age'].fillna(np.round(df['Age'].mean()))
df['Age'] = df['Age'].fillna(df['Age'].mode())
df

Name   Age Gender  Height  Weight
0    Alice  25.0      F     5.5    65.0
1      Bob  35.0      M     6.0    80.0
2  Charlie  35.0    NaN     NaN    77.0
3    David  45.0      M     5.8     NaN
4   Edward  55.0      M     5.9    88.0
5    Frank  40.0      M     6.1    90.0
6   George  65.0      M     6.2    75.0
7     Hank  35.0      M     5.9    77.0
8    Alice  25.0      F     5.5    65.0

In [24]:
df['Gender'] = df['Gender'].fillna(df['Gender'].mode()[0])
df

Name   Age Gender  Height  Weight
0    Alice  25.0      F     5.5    65.0
1      Bob  35.0      M     6.0    80.0
2  Charlie  35.0      M     NaN    77.0
3    David  45.0      M     5.8     NaN
4   Edward  55.0      M     5.9    88.0
5    Frank  40.0      M     6.1    90.0
6   George  65.0      M     6.2    75.0
7     Hank  35.0      M     5.9    77.0
8    Alice  25.0      F     5.5    65.0

In [25]:
df['Height'] = df['Height'].fillna(np.round(df['Height'].mean()))
df

Name   Age Gender  Height  Weight
0    Alice  25.0      F     5.5    65.0
1      Bob  35.0      M     6.0    80.0
2  Charlie  35.0      M     6.0    77.0
3    David  45.0      M     5.8     NaN
4   Edward  55.0      M     5.9    88.0
5    Frank  40.0      M     6.1    90.0
6   George  65.0      M     6.2    75.0
7     Hank  35.0      M     5.9    77.0
8    Alice  25.0      F     5.5    65.0

In [26]:
df['Weight'] = df['Weight'].fillna(np.round(df['Weight'].mean()))
df

Name   Age Gender  Height  Weight
0    Alice  25.0      F     5.5    65.0
1      Bob  35.0      M     6.0    80.0
2  Charlie  35.0      M     6.0    77.0
3    David  45.0      M     5.8    77.0
4   Edward  55.0      M     5.9    88.0
5    Frank  40.0      M     6.1    90.0
6   George  65.0      M     6.2    75.0
7     Hank  35.0      M     5.9    77.0
8    Alice  25.0      F     5.5    65.0

In [27]:
df = df.drop_duplicates()
df

Name   Age Gender  Height  Weight
0    Alice  25.0      F     5.5    65.0
1      Bob  35.0      M     6.0    80.0
2  Charlie  35.0      M     6.0    77.0
3    David  45.0      M     5.8    77.0
4   Edward  55.0      M     5.9    88.0
5    Frank  40.0      M     6.1    90.0
6   George  65.0      M     6.2    75.0
7     Hank  35.0      M     5.9    77.0

In [28]:
df.dtypes

Name       object
Age       float64
Gender     object
Height    float64
Weight    float64
dtype: object

In [29]:
df = df.copy()

In [30]:
df['Age'] = df['Age'].astype(int)
df.dtypes

Name       object
Age         int32
Gender     object
Height    float64
Weight    float64
dtype: object

In [31]:
df

Name  Age Gender  Height  Weight
0    Alice   25      F     5.5    65.0
1      Bob   35      M     6.0    80.0
2  Charlie   35      M     6.0    77.0
3    David   45      M     5.8    77.0
4   Edward   55      M     5.9    88.0
5    Frank   40      M     6.1    90.0
6   George   65      M     6.2    75.0
7     Hank   35      M     5.9    77.0

In [32]:
df.to_csv('mydataset-new.csv', index=False)

In [33]:
data = [[50, True], [40, False], [30, False]]
label_rows = ["Sally", "Mary", "John"]
label_cols = ["age", "qualified"]

df = pd.DataFrame(data, label_rows, label_cols)
df

age  qualified
Sally   50       True
Mary    40      False
John    30      False

In [34]:
df.loc["Mary", "age"]

40

In [35]:
data = pd.DataFrame({'Brand': ['Maruti', 'Hyundai', 'Tata',
							'Mahindra', 'Maruti', 'Hyundai',
							'Renault', 'Tata', 'Maruti'],
					'Year': [2012, 2014, 2011, 2015, 2012,
							2016, 2014, 2018, 2019],
					'Kms Driven': [50000, 30000, 60000,
									25000, 10000, 46000,
									31000, 15000, 12000],
					'City': ['Gurgaon', 'Delhi', 'Mumbai',
							'Delhi', 'Mumbai', 'Delhi',
							'Mumbai', 'Chennai', 'Ghaziabad'],
					'Mileage': [28, 27, 25, 26, 28,
								29, 24, 21, 24]})

display(data)

Brand  Year  Kms Driven       City  Mileage
0    Maruti  2012       50000    Gurgaon       28
1   Hyundai  2014       30000      Delhi       27
2      Tata  2011       60000     Mumbai       25
3  Mahindra  2015       25000      Delhi       26
4    Maruti  2012       10000     Mumbai       28
5   Hyundai  2016       46000      Delhi       29
6   Renault  2014       31000     Mumbai       24
7      Tata  2018       15000    Chennai       21
8    Maruti  2019       12000  Ghaziabad       24

In [36]:
data.loc[(data.Brand == 'Maruti') & (data.Mileage > 25)]

Brand  Year  Kms Driven     City  Mileage
0  Maruti  2012       50000  Gurgaon       28
4  Maruti  2012       10000   Mumbai       28

In [37]:
data.loc[0:3,:]

Brand  Year  Kms Driven     City  Mileage
0    Maruti  2012       50000  Gurgaon       28
1   Hyundai  2014       30000    Delhi       27
2      Tata  2011       60000   Mumbai       25
3  Mahindra  2015       25000    Delhi       26

In [38]:
data.loc[:, ['Brand', 'City']]

Brand       City
0    Maruti    Gurgaon
1   Hyundai      Delhi
2      Tata     Mumbai
3  Mahindra      Delhi
4    Maruti     Mumbai
5   Hyundai      Delhi
6   Renault     Mumbai
7      Tata    Chennai
8    Maruti  Ghaziabad

In [39]:
data.loc[:, 'Year':'City']

Year  Kms Driven       City
0  2012       50000    Gurgaon
1  2014       30000      Delhi
2  2011       60000     Mumbai
3  2015       25000      Delhi
4  2012       10000     Mumbai
5  2016       46000      Delhi
6  2014       31000     Mumbai
7  2018       15000    Chennai
8  2019       12000  Ghaziabad

In [40]:
data.loc[data.City == 'Delhi', 'Brand']

1     Hyundai
3    Mahindra
5     Hyundai
Name: Brand, dtype: object

In [41]:
data.columns

Index(['Brand', 'Year', 'Kms Driven', 'City', 'Mileage'], dtype='object')

In [42]:
data.iloc[0:2]

Brand  Year  Kms Driven     City  Mileage
0   Maruti  2012       50000  Gurgaon       28
1  Hyundai  2014       30000    Delhi       27

In [43]:
data.iloc[4:, :3]

Brand  Year  Kms Driven
4   Maruti  2012       10000
5  Hyundai  2016       46000
6  Renault  2014       31000
7     Tata  2018       15000
8   Maruti  2019       12000

In [44]:
data.iloc[0:4, :]

Brand  Year  Kms Driven     City  Mileage
0    Maruti  2012       50000  Gurgaon       28
1   Hyundai  2014       30000    Delhi       27
2      Tata  2011       60000   Mumbai       25
3  Mahindra  2015       25000    Delhi       26

In [45]:
data.loc[0:4, :]

Brand  Year  Kms Driven     City  Mileage
0    Maruti  2012       50000  Gurgaon       28
1   Hyundai  2014       30000    Delhi       27
2      Tata  2011       60000   Mumbai       25
3  Mahindra  2015       25000    Delhi       26
4    Maruti  2012       10000   Mumbai       28

In [48]:
data.loc[(data['Year'] > 2012), ['Brand', 'City']]

Brand       City
1   Hyundai      Delhi
3  Mahindra      Delhi
5   Hyundai      Delhi
6   Renault     Mumbai
7      Tata    Chennai
8    Maruti  Ghaziabad

In [ ]:
data.loc[(data.Year < 2015), ['Mileage']] = data.loc[:, 'Mileage'].mean().astype(int)
data

Brand  Year  Kms Driven       City  Mileage
0    Maruti  2012       50000    Gurgaon       25
1   Hyundai  2014       30000      Delhi       25
2      Tata  2011       60000     Mumbai       25
3  Mahindra  2015       25000      Delhi       26
4    Maruti  2012       10000     Mumbai       25
5   Hyundai  2016       46000      Delhi       29
6   Renault  2014       31000     Mumbai       25
7      Tata  2018       15000    Chennai       21
8    Maruti  2019       12000  Ghaziabad       24

# Numpy

In [ ]:
import numpy as np

In [ ]:
myList = [[1,2,3],[4,5,6],[7,8,9]]
myList

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
myArray = np.array(myList)
myArray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
myArray.shape

(3, 3)

In [ ]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [ ]:
np.arange(4,40,4)

array([ 4,  8, 12, 16, 20, 24, 28, 32, 36])

In [ ]:
np.zeros(4, dtype=int)

array([0, 0, 0, 0])

In [ ]:
np.zeros((3,4), dtype=[('x', 'int'), ('y', 'float')])

array([[(0, 0.), (0, 0.), (0, 0.), (0, 0.)],
       [(0, 0.), (0, 0.), (0, 0.), (0, 0.)],
       [(0, 0.), (0, 0.), (0, 0.), (0, 0.)]],
      dtype=[('x', '<i4'), ('y', '<f8')])

In [ ]:
np.identity(3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [ ]:
np.linspace(1, 15, 6)
# step = (15-1/6-1)

array([ 1. ,  3.8,  6.6,  9.4, 12.2, 15. ])

In [ ]:
my1DArray = np.arange(12)
my1DArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
my2DArray = my1DArray.reshape(4,3)
my2DArray

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
my2DArray[1:3]

array([[3, 4, 5],
       [6, 7, 8]])

In [ ]:
my2DArray[1:,1:3]

array([[ 4,  5],
       [ 7,  8],
       [10, 11]])

In [ ]:
my2DArray[2][1]

7

In [ ]:
copyArray = myArray.copy()
copyArray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
copyArray[:] = 777
copyArray

array([[777, 777, 777],
       [777, 777, 777],
       [777, 777, 777]])

In [ ]:
my2DArray[my2DArray>5]

array([ 6,  7,  8,  9, 10, 11])

In [ ]:
my2DArray * 3

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24],
       [27, 30, 33]])

In [ ]:
myArray + 6

array([[ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [ ]:
sq = np.sqrt(myArray)
sq

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [ ]:
sq = sq.astype(int)
sq

array([[1, 1, 1],
       [2, 2, 2],
       [2, 2, 3]])

In [ ]:
np.dot(myArray, copyArray)

array([[ 4662,  4662,  4662],
       [11655, 11655, 11655],
       [18648, 18648, 18648]])

In [ ]:
np.transpose(sq)

array([[1, 2, 2],
       [1, 2, 2],
       [1, 2, 3]])

In [ ]:
np.mean(sq)

1.7777777777777777

In [ ]:
np.std(sq)

0.6285393610547089

In [ ]:
np.cov(sq).astype(int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
newarr

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [ ]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr3 = np.concatenate((arr1, arr2))
arr3

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr3 = np.concatenate((arr1, arr2), axis=1)
arr3

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2), axis=1)
arr

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.hstack((arr1, arr2))
arr

array([1, 2, 3, 4, 5, 6])

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.vstack((arr1, arr2))
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = np.array_split(arr, 3)
newarr

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8])]

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 4)
newarr

[array([1, 2]), array([3, 4]), array([5]), array([6])]

In [ ]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
newarr = np.array_split(arr, 3)
newarr

[array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]),
 array([[ 9, 10],
        [11, 12]])]

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.array_split(arr, 2, axis=1)
newarr

[array([[ 1,  2],
        [ 4,  5],
        [ 7,  8],
        [10, 11],
        [13, 14],
        [16, 17]]),
 array([[ 3],
        [ 6],
        [ 9],
        [12],
        [15],
        [18]])]