In [1]:
import numpy as np

In [2]:
myList = [[1,2,3], [4,5,6], [7,8,9]]

In [3]:
myArray = np.array(myList)

In [4]:
myArray.shape

(3, 3)

In [5]:
np.arange(0,7)

array([0, 1, 2, 3, 4, 5, 6])

In [6]:
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [7]:
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [10]:
np.linspace(1, 15, 6)

array([ 1. ,  3.8,  6.6,  9.4, 12.2, 15. ])